In [2]:
import pandas as pd
import matplotlib as plt

In [3]:
salaeCSVfile = '/Users/johnmarshall/Documents/Analysis/miniscope_analysis/miniscope_T_maze/m328/raw_328.csv'
salaeData = pd.read_csv(salaeCSVfile)
timestampfileSession1 = pd.read_table('/Users/johnmarshall/Documents/Analysis/miniscope_analysis/miniscope_T_maze/m328/timeStampsMiniscope_16_44_25.csv', delimiter=',')
timestampfileSession2 = pd.read_table('/Users/johnmarshall/Documents/Analysis/miniscope_analysis/miniscope_T_maze/m328/timeStampsMiniscope_17_56_20.csv', delimiter=',')

In [4]:
salaeData

,Time [s],Channel 0,Channel 1,Channel 2,Channel 3,Channel 4,Channel 5,Channel 6,Channel 7,Channel 8,Channel 9,Channel 10,Channel 11,Channel 12,Channel 13,Channel 14,Channel 15
0,0.000000,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1,75.184965,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,75.219546,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3,75.252180,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,75.285787,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231108,8103.506708,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
231109,8103.539440,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
231110,8103.573055,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
231111,8103.607342,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
231112,8126.054400,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [5]:
salaeData['Channel 10'][salaeData['Channel 10']>0]

426       1
427       1
428       1
429       1
430       1
         ..
228943    1
228944    1
228945    1
228946    1
228947    1
Name: Channel 10, Length: 1705, dtype: int64

In [6]:
timestampfileSession1

        Frame Number  Time Stamp (ms)  Buffer Index
0                  0               -5             0
1                  1               30             0
2                  2               62             0
3                  3               96             0
4                  4              132             0
...              ...              ...           ...
119225        119225          4008142             0
119226        119226          4008178             0
119227        119227          4008209             0
119228        119228          4008243             0
119229        119229          4008278             0

[119230 rows x 3 columns]

In [7]:
timestampfileSession2

        Frame Number  Time Stamp (ms)  Buffer Index
0                  0               -7             2
1                  1               29             3
2                  2               63             2
3                  3               95             1
4                  4              133             0
...              ...              ...           ...
110456        110456          3714244             0
110457        110457          3714277             0
110458        110458          3714313             0
110459        110459          3714345             0
110460        110460          3714381             0

[110461 rows x 3 columns]

In [15]:
#channel 10 reports start of trial?
#channle 11 reports end of trial?
salaeData['Channel 10'][salaeData['Channel 10']>0]

426       1
427       1
428       1
429       1
430       1
         ..
228943    1
228944    1
228945    1
228946    1
228947    1
Name: Channel 10, Length: 1705, dtype: int64

In [ ]:
# separate salae si